---
'https://cmdb.oit.duke.edu':
  token: $ vault read -field token secret/shared_service_accounts/cmdb
  fresh_time: 24h
  username: vault read -field username secret/shared_service_accounts/cmdb
  password: $ vault read -field password secret/shared_service_accounts/cmdb
