---
'https://cmdb.oit.duke.edu':
  token: $ vault kv get -field=token ssi-systems/kv/shared_service_accounts/cmdb
  fresh_time: 24h
  username: $ vault kv get -field=username ssi-systems/kv/shared_service_accounts/cmdb
  password: $ vault kv get -field=password ssi-systems/kv/shared_service_accounts/cmdb
