---
duke:
  username: $ lpass show servicenow-api --username
  password: $ lpass show servicenow-api --password
  instance: duke
  whoami: $ whoami
dukesandbox:  
  username: $ lpass show 'Service Now Sandbox Account' --username
  password: $ lpass show 'Service Now Sandbox Account' --password
  instance: dukesandbox
  whoami: $ whoami
