add_newline = false

[aws]
disabled = true

[cmake]
disabled = true

[cmd_duration]
min_time = 500
format = "[$duration]($style) "

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true

[custom.vault]
command = "echo $VAULT_ADDR"
when = "[ ! -z $VAULT_ADDR ]"
symbol = '🔐'
format = "[$symbol $output]($style) "
description = "VAULT_ADDR is set to a specific address"

[custom.clockworks]
command = "echo $CLOCKWORKS_BASE_URL"
when = "[ ! -z $CLOCKWORKS_BASE_URL ]"
symbol = '🕰 '
format = "[$symbol $output]($style) "
description = "CLOCKWORKS_BASE_URL is set to a specific address"

[custom.vault_token]
command = "echo Ⓣ"
when = "[ ! -z $VAULT_TOKEN ]"
format = '$output '

[custom.op]
command = "echo (math -s0 \\($OP_EXPIRATION_TIME - (date -u +%s)\\) / 60)m"
when = "[ ! -z $OP_EXPIRATION_TIME ] && [ (math -s0 \\($OP_EXPIRATION_TIME - (date -u +%s)\\) / 60) -gt 0 ]"
symbol = '1️⃣ '
format = "[$symbol $output]($style) "
description = "1Password is logged in"
